spring:
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:ltc-hack2026-team27}
      bucket-name: ${GCS_BUCKET_NAME:pixelproof-dev}
  application:
    name: reboot2026-pixelproof-bgv-api

  bigquery:
    dataset-name: ${BIGQUERY_DATASET_NAME:pixelproof}
    table-name: ${BIGQUERY_TABLE_NAME:document-verification}

gcs:
  bucket-name: pixelproof-dev

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

hyperledger:
  channel-name: ${HYPERLEDGER_CHANNEL_NAME:mychannel}
  chaincode-name: ${HYPERLEDGER_CHAINCODE_NAME:auditchaincode}
  msp-id: ${HYPERLEDGER_MSP_ID:Org1MSP}
  peer-endpoint: ${HYPERLEDGER_PEER_ENDPOINT:localhost:7051}
  gateway-peer: ${HYPERLEDGER_GATEWAY_PEER:peer0.org1.example.com}
  crypto-path: ${HYPERLEDGER_CRYPTO_PATH:/workspace/crypto-config}
  wallet-path: ${HYPERLEDGER_WALLET_PATH:/workspace/wallet}
  connection-profile: ${HYPERLEDGER_CONNECTION_PROFILE:/workspace/connection-org1.json}


vertex-ai:
  enabled: ${VERTEX_AI_ENABLED:true}
  project-id: ${VERTEX_AI_PROJECT_ID:ltc-hack2026-team27}
  location: ${VERTEX_AI_LOCATION:us-central1} #need to update original region
  model: ${VERTEX_AI_MODEL:gemini-1.5-flash}