spring:
  cloud:
    gcp:
      project-id: ltc-hack2026-team27
      bucket-name: pixelproof-dev
      credentials:
        location: file:C:\Users\Dell\Documents\GitHub\reboot2026-pixelproof-api\src\main\resources\ltc-hack2026-team27.json
  application:
    name: reboot2026-pixelproof-bgv-api

  bigquery:
    dataset-name: pixelproof
    table-name: document-verification
    credentials:
      location: classpath:ltc-hack2026-team27.json

gcs:
  bucket-name: pixelproof-dev

server:
  port: 8085
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

hyperledger:
  channel-name: mychannel
  chaincode-name: auditchaincode
  msp-id: Org1MSP
  peer-endpoint: localhost:7051
  gateway-peer: peer0.org1.example.com
  crypto-path: C:/hyperledger-network/crypto-config
  wallet-path: C:/hyperledger-network/wallet
  connection-profile: C:/hyperledger-network/connection-org1.json


vertex-ai:
  enabled: ${VERTEX_AI_ENABLED:true}
  project-id: ${VERTEX_AI_PROJECT_ID:ltc-hack2026-team27}
  location: ${VERTEX_AI_LOCATION:us-central1} #need to update original region
  model: ${VERTEX_AI_MODEL:gemini-1.5-flash}